In [1]:
import pandas as pd

In [2]:
data=pd.read_json('News_Category_Dataset_v3.json',lines=True)

In [3]:
data.head()

link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date  
0 2022-09-23  
1 2022-09-23  
2 2022-09-23  
3 2022-09-23  
4 2022-09-22

In [4]:
## Data Exploration

In [5]:
data.shape

(209527, 6)

In [6]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [7]:
data=data['short_description'].head(20000)

In [8]:
data

0        Health experts said it is too early to predict...
1        He was subdued by passengers and crew when he ...
2        "Until you have a dog you don't understand wha...
3        "Accidentally put grown-up toothpaste on my to...
4        Amy Cooper accused investment firm Franklin Te...
                               ...                        
19995    He and his wife Grace would be granted full im...
19996    Transition is the name of the game in the Midd...
19997    The breakdown of coalition talks has plunged G...
19998    In a major, thorough and truly important piece...
19999    In recent weeks, Saudi Arabia has become more ...
Name: short_description, Length: 20000, dtype: object

In [9]:
data[0]

'Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall.'

In [10]:
data.isnull().sum()

np.int64(0)

In [11]:
data.duplicated().sum()

np.int64(66)

In [12]:
## Data Cleaning

In [13]:
data.drop_duplicates(inplace=True)

In [14]:
data.duplicated().sum()

np.int64(0)

In [15]:
data.shape

(19934,)

In [16]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [17]:
tokenizer=Tokenizer(oov_token='<OOV>')

In [18]:
tokenizer.fit_on_texts(data)

In [19]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'for': 8,
 'is': 9,
 'on': 10,
 'said': 11,
 'that': 12,
 'was': 13,
 'with': 14,
 'his': 15,
 'it': 16,
 'at': 17,
 'he': 18,
 'are': 19,
 'as': 20,
 'has': 21,
 'have': 22,
 'an': 23,
 'from': 24,
 'be': 25,
 'president': 26,
 'this': 27,
 'trump': 28,
 '”': 29,
 'about': 30,
 'by': 31,
 'her': 32,
 'new': 33,
 'not': 34,
 'but': 35,
 'after': 36,
 'you': 37,
 'who': 38,
 'i': 39,
 'will': 40,
 'one': 41,
 'people': 42,
 'more': 43,
 'their': 44,
 'been': 45,
 'year': 46,
 'out': 47,
 'former': 48,
 'they': 49,
 'up': 50,
 'she': 51,
 'u': 52,
 'were': 53,
 's': 54,
 'all': 55,
 'we': 56,
 'just': 57,
 'what': 58,
 'first': 59,
 'over': 60,
 'had': 61,
 'house': 62,
 'than': 63,
 'says': 64,
 'when': 65,
 'two': 66,
 'no': 67,
 'would': 68,
 'or': 69,
 'some': 70,
 'like': 71,
 'state': 72,
 "it's": 73,
 'into': 74,
 'show': 75,
 'if': 76,
 'also': 77,
 'time': 78,
 'say': 79,
 'last': 80,
 'your': 81,
 'could

In [20]:
len(tokenizer.word_index)

26343

In [21]:
data=tokenizer.texts_to_sequences(data)

In [22]:
data

[[163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517,
  198,
  4125,
  5,
  2,
  33,
  13518,
  2,
  52,
  54,
  1298,
  8,
  2,
  897],
 [18,
  13,
  13519,
  31,
  2072,
  6,
  2540,
  65,
  18,
  2169,
  3,
  2,
  107,
  5,
  2,
  3038,
  36,
  2,
  4126,
  231,
  3,
  2,
  52,
  54,
  9667,
  247,
  7,
  973,
  1037],
 [507, 37, 22, 4, 1339, 37, 192, 1515, 58, 82, 25, 7729],
 [4127,
  258,
  3534,
  50,
  9668,
  10,
  93,
  13520,
  13521,
  6,
  18,
  9669,
  71,
  39,
  13,
  3829,
  15,
  3277,
  14,
  4,
  1064,
  13522,
  9670,
  7,
  13523,
  7730],
 [2073,
  2709,
  133,
  4496,
  1516,
  5027,
  13524,
  5,
  7731,
  2541,
  32,
  6,
  9671,
  32,
  4,
  747,
  36,
  196,
  5,
  2,
  1261,
  801,
  2397,
  338,
  784],
 [2,
  3830,
  46,
  94,
  191,
  13,
  591,
  402,
  17,
  2,
  403,
  1064,
  1517,
  10,
  637,
  51,
  13,
  199,
  418,
  307,
  36,
  32,
  186,
  353,
  32,
  898,
  392,
  11],
 [1183,
  12,


In [23]:
input_sequences=[]
for seq in data:
    if len(seq)<2:
        continue
    for i in range(1,len(seq)):
        ngram=seq[:i+1]
        input_sequences.append(ngram)

In [24]:
input_sequences

[[163, 352],
 [163, 352, 11],
 [163, 352, 11, 16],
 [163, 352, 11, 16, 9],
 [163, 352, 11, 16, 9, 162],
 [163, 352, 11, 16, 9, 162, 544],
 [163, 352, 11, 16, 9, 162, 544, 3],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50, 14],
 [163, 352, 11, 16, 9, 162, 544, 3, 5026, 347, 1514, 68, 2396, 50, 14, 2],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13517,
  198],
 [163,
  352,
  11,
  16,
  9,
  162,
  544,
  3,
  5026,
  347,
  1514,
  68,
  2396,
  50,
  14,
  2,
  13

In [25]:
max_len=max([len(i) for i in input_sequences])

In [26]:
max_len

44

In [27]:
input=pad_sequences(input_sequences,padding='pre',maxlen=max_len)

In [28]:
input

array([[   0,    0,    0, ...,    0,  163,  352],
       [   0,    0,    0, ...,  163,  352,   11],
       [   0,    0,    0, ...,  352,   11,   16],
       ...,
       [   0,    0,    0, ...,   10, 3812,  559],
       [   0,    0,    0, ..., 3812,  559,  354],
       [   0,    0,    0, ...,  559,  354,   12]], dtype=int32)

In [29]:
input[50]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,    18,    13, 13519,    31,  2072,     6,
        2540,    65,    18,  2169,     3,     2,   107,     5,     2,
        3038,    36,     2,  4126,   231,     3,     2,    52],
      dtype=int32)

In [30]:
X=input[:,:-1]
y=input[:,-1]

In [31]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 163], dtype=int32)

In [32]:
X.shape

(300014, 43)

In [33]:
y.shape

(300014,)

In [34]:
y=np.array(y)

In [35]:
## Modelling

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
X_train.shape

(240011, 43)

In [39]:
vocab_size=len(tokenizer.word_index)+1

In [40]:
vocab_size

26344

In [41]:
max_len=X.shape[1]

In [42]:
model=Sequential([Embedding(vocab_size,128,input_length=max_len),LSTM(256),Dense(vocab_size,activation='softmax')])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [43]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [44]:
model.build(input_shape=(None,max_len))

In [45]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     3,372,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 26344)          │     6,770,408 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,536,680 (40.19 MB)

 Trainable params: 10,536,680 (40.19 MB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.fit(X_train,y_train,epochs=30,validation_data=(X_test,y_test))

Epoch 1/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 116s 15ms/step - accuracy: 0.2963 - loss: 3.8738 - val_accuracy: 0.1317 - val_loss: 7.2985
Epoch 2/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 117s 16ms/step - accuracy: 0.3623 - loss: 3.3707 - val_accuracy: 0.1289 - val_loss: 7.5322
Epoch 3/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 118s 16ms/step - accuracy: 0.4270 - loss: 2.9480 - val_accuracy: 0.1242 - val_loss: 7.7505
Epoch 4/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 118s 16ms/step - accuracy: 0.4854 - loss: 2.6045 - val_accuracy: 0.1190 - val_loss: 7.9628
Epoch 5/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 117s 16ms/step - accuracy: 0.5343 - loss: 2.3173 - val_accuracy: 0.1172 - val_loss: 8.2075
Epoch 6/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 116s 15ms/step - accuracy: 0.5792 - loss: 2.0817 - val_accuracy: 0.1123 - val_loss: 8.4111
Epoch 7/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 117s 16ms/step - accuracy: 0.6189 - loss: 1.8723 - val_accuracy: 0.1101 - val_loss: 8.6354
Epoch 8/30
7501/7501 ━━━━━━━━━━━━━━━━━━━━ 116s 16ms/step - accuracy: 

In [50]:
model.save('nextword_model.h5')

In [51]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)